# Gemfile structure:
#   Gemfile
#       Gemfile.other
#       Gemfile.rails
#           Gemfile.rails.test

source 'https://rubygems.org'

gem 'rake', '>= 10.1'
gem 'sqlite3', '>= 1.3.3'

group :doc do
  gem 'rdoc'
  gem 'sdoc'
end

gem 'rspec', group: :test
gem 'simplecov', git: 'https://github.com/colszowka/simplecov', tag: 'v0.10.0'

group :git_sources do
  gem 'mime-types', git: 'https://github.com/mime-types/ruby-mime-types/'
  gem 'multi_json', git: 'https://github.com/intridea/multi_json'
  gem 'colorize', git: 'https://github.com/fazibear/colorize'
end

root = File.expand_path('..', __FILE__)
eval_gemfile File.join(root, 'Gemfile.rails')
eval_gemfile File.join(root, 'Gemfile.other')

require File.join(root, '../bundler/multi_lockfile_hack.rb')
extend Bundler::MultiLockfileHack

generate_lockfile(groups: :doc, lockfile: 'doc.lock')
generate_lockfile(groups: [:doc, :test], lockfile: 'doc.test.lock')
generate_lockfile(gemfile: File.join(root, 'Gemfile.other'), lockfile: 'other.lock')
generate_lockfile(gemfile: File.join(root, 'Gemfile.rails'), groups: :test, lockfile: 'rails.test.lock')
generate_lockfile(groups: :git_sources, lockfile: 'git_only.lock')
